# CREATING CUSTOMER TABLE NAMED CUSTOMER_T

CREATE TABLE CUSTOMER_T (ID NUMBER,
                         NAME VARCHAR(50) PRIMARY KEY,
                         GENDER VARCHAR(5),
                         MOBILE VARCHAR(10) NOT NULL,
                         EMAIL VARCHAR(50) );
                         
INSERT INTO CUSTOMER_T VALUES (100, 'RAM', 'M', '2233442233', 'RAM@GMAIL.COM');
INSERT INTO CUSTOMER_T VALUES (101, 'RAMAN', 'M', '9988334400', 'RAMAN@GMAIL.COM');
INSERT INTO CUSTOMER_T VALUES (102, 'SIYA', 'F', '1234512345', 'SIYA@GMAIL.COM');
INSERT INTO CUSTOMER_T VALUES (103, 'MILI', 'F', '7676564513', 'MILI@GMAIL.COM');
INSERT INTO CUSTOMER_T VALUES (104, 'RAMANA', 'M', '2233442290', 'RAMANA@GMAIL.COM');

SELECT * FROM CUSTOMER_T;

........................................................................

CREATE TABLE CUSTOMER_DATA (
C_ID NUMBER(2) PRIMARY KEY,
C_NAME VARCHAR2(100),
PHONE NUMBER(10) UNIQUE CHECK(LENGTH(PHONE) = 10)
);

INSERT INTO CUSTOMER_DATA VALUES (11, 'RAMA', 8787890936);
INSERT INTO CUSTOMER_DATA VALUES (12, 'RIYA', 3423129023);
INSERT INTO CUSTOMER_DATA VALUES (13, 'RAMA', 4589093456);
INSERT INTO CUSTOMER_DATA VALUES (14, 'PRIYA', 4567387909)
;

SELECT * FROM CUSTOMER_DATA;

................................................................

CREATE TABLE TRANSACTIONS (
T_ID NUMBER(5) PRIMARY KEY,
ITEM_ID NUMBER(3),
CUSTOMER_ID NUMBER(2),
FOREIGN KEY (ITEM_ID) REFERENCES INVENTORY(ITEM_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_DATA(C_ID)
);

INSERT INTO TRANSACTIONS VALUES (12345, 1, 11);
INSERT INTO TRANSACTIONS VALUES (12346, 1, 13);
INSERT INTO TRANSACTIONS VALUES (22345, 2, 11);
INSERT INTO TRANSACTIONS VALUES (13345, 2, 12);
INSERT INTO TRANSACTIONS VALUES (12355, 2, 14);
INSERT INTO TRANSACTIONS VALUES (12344, 3, 12);
INSERT INTO TRANSACTIONS VALUES (12333, 3, 13);
INSERT INTO TRANSACTIONS VALUES (12315, 3, 14);

SELECT * FROM TRANSACTIONS;

.............................................................
