
--CREATING CUSTOMER TABLE NAMED CUSTOMER_T

CREATE TABLE CUSTOMER_T (ID NUMBER,
                         NAME VARCHAR(50) PRIMARY KEY,
                         GENDER VARCHAR(5),
                         MOBILE VARCHAR(10) NOT NULL,
                         EMAIL VARCHAR(50) );
                         
INSERT INTO CUSTOMER_T VALUES (100, 'RAM', 'M', '2233442233', 'RAM@GMAIL.COM');
INSERT INTO CUSTOMER_T VALUES (101, 'RAMAN', 'M', '9988334400', 'RAMAN@GMAIL.COM');
INSERT INTO CUSTOMER_T VALUES (102, 'SIYA', 'F', '1234512345', 'SIYA@GMAIL.COM');
INSERT INTO CUSTOMER_T VALUES (103, 'MILI', 'F', '7676564513', 'MILI@GMAIL.COM');
INSERT INTO CUSTOMER_T VALUES (104, 'RAMANA', 'M', '2233442290', 'RAMANA@GMAIL.COM');

SELECT * FROM CUSTOMER_T;

........................................................................

  -- CREATE PRODUCT TABLE NAMED PRODUCT_T
  
  CREATE TABLE PRODUCT_T (P_ID NUMBER PRIMARY KEY,
                        P_NAME VARCHAR(50) NOT NULL,
                        P_CATEGORY VARCHAR(30),
                        UNIT_PRICE NUMBER NOT NULL,
                        PRODUCT_DESCRIPTION VARCHAR(200) );
                        
INSERT INTO PRODUCT_T VALUES (10, 'SHIRT', 'CLOTH', 550, 'LINEN BLACK SMALL SIZE');
INSERT INTO PRODUCT_T VALUES (11, 'FRYING PAN', 'UTENSIL', 700, 'BLACK MEDIUM SIZE');
INSERT INTO PRODUCT_T VALUES (15, 'HANGER', 'UTILITY', 2200, 'PLASTIC HANGERS');
INSERT INTO PRODUCT_T VALUES (18, 'KURTHI', 'CLOTH', 400, 'COTTON WHITE EXTRA LARGE SIZE');
INSERT INTO PRODUCT_T VALUES (20, 'PISTACIO', 'FOOD', 1300, 'SALTED CRUNCHY PISTA');

SELECT * FROM PRODUCT_T;


................................................................



.............................................................
